# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

panel_custom:
  - name: Supervisor
    url_path: hassio/system # url_path needs to be unique for each panel_custom config
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant # https://materialdesignicons.com/
    module_url: /local/panel-redirect.js # 'local' is '/config/www/'

logger:
  default: info
  logs:
    pymodbus.transaction: debug

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

modbus:
  - name: SmartHouse
    type: tcp
    host: 192.168.5.88
    port: 502
    lights:
      - name: "(Fx) Lys enhætte"
        address: 4434
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4434
          state_on: 1
          state_off: 0
      - name: "(Fx) Spisestue - Dimmable light"
        address: 4588
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4588
          state_on: 1
          state_off: 0
      - name: "(Fx) Dørlås"
        address: 4648
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4648
          state_on: 1
          state_off: 0
      - name: "(Fx) Loftlampe"
        address: 4720
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4720
          state_on: 1
          state_off: 0
      - name: "(Fx) Trappen - Light function"
        address: 4540
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4540
          state_on: 1
          state_off: 0
      - name: "(Fx) Multi (1_sal) - Light function"
        address: 4842
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4842
          state_on: 1
          state_off: 0
      - name: "(Fx) Stuen - Light function Turn all off"
        address: 8150
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 8150
          state_on: 1
          state_off: 0
      - name: "(Fx) 1_ Sal - Light function Turn all off"
        address: 12840
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 12840
          state_on: 1
          state_off: 0
      - name: "(Fx) Root - Light function Turn all off (delay)"
        address: 12866
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 12866
          state_on: 1
          state_off: 0
      - name: "(Fx) Garage - Port åbne/lukke"
        address: 12892
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 12892
          state_on: 1
          state_off: 0
      - name: "(Fx) Hall - Light function"
        address: 12970
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 12970
          state_on: 1
          state_off: 0
      - name: "(Fx) Metro Therm (bloker varme)"
        address: 12996
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 12996
          state_on: 1
          state_off: 0
      - name: "(Fx) Garage - Port status"
        address: 4350
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 4350
          state_on: 1
          state_off: 0
    sensors:
      - name: "custom_garage_port"
        address: 4350
        slave: 1
        data_type: uint16
        input_type: holding
        scan_interval: 1
      - name: "sensor_fxkokken_smartlight"
        address: 359
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxbadevarelse_smartlight"
        address: 928
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxmellemgang_smartlight"
        address: 1428
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxhall_smartlight"
        address: 1928
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxvarelse_smartlight"
        address: 2428
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxviktualierum_smartlight"
        address: 2928
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxspisestue_smartlight"
        address: 3428
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxsovevarelse_smartlight"
        address: 4838
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxbryggers_smartlight"
        address: 5658
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxforan_smartlight"
        address: 6158
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxmulti1_sal_smartlight"
        address: 6658
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxprojektor_smartlightbagved1_sal"
        address: 7158
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxudestue1_sal_smartlight"
        address: 7658
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxvarelsenord1_sal_smartlight"
        address: 8215
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxvarelseost1_sal_smartlight"
        address: 8715
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxgarage_smartlight"
        address: 9215
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxbagved_smartlight"
        address: 9715
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxskur_smartlight"
        address: 10215
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxprojektor_smartlightforan"
        address: 10895
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxbadevarelse1_sal_smartlight"
        address: 11447
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxterassestuen_smartlight"
        address: 12011
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1
      - name: "sensor_fxterasse1_sal_smartlight"
        address: 12511
        slave: 1
        data_type: uint16
        input_type: input
        scan_interval: 1

light smarthouse: !include smarthouse-lights.yaml
